apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: acrweek10.azurecr.io/order_service:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: order-db
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PRODUCT_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  ports:
    - port: 8001       # External port for accessing service
      targetPort: 8000 # Container port
  selector:
    app: order-service
