apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: <ACR_NAME>.azurecr.io/order_service:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: order-db
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PRODUCT_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: staging
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8000
  selector:
    app: order-service
