apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: acrweek10.azurecr.io/product_service:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: product-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PRODUCT_DB
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: staging
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: product-service
