apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Postgres credentials (base64 encoded: echo -n 'postgres' | base64)
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=

  # Azure Storage credentials
  # echo -n 'your_account_name' | base64
  AZURE_STORAGE_ACCOUNT_NAME: c3RyZ3dlZWsxMA==
  # echo -n 'your_storage_account_key_string' | base64
  AZURE_STORAGE_ACCOUNT_KEY: ZnA1OHRwanphREtnVHI3ZDRHNmlwM3FTendqdktvTFdvbysrZlVKL1VpV3hZQzdwSVFmUG94Sjg0ZHAyd1NYZnZ6NnhtR0JSVDc3eStBU3RlRmR3anc9PQ==
