name: CD - Production Deployment

# Trigger: merge to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}

      - name: Apply ConfigMaps & Secrets
        run: kubectl apply -f k8s/configmaps.yaml -f k8s/secrets.yaml -n production

      - name: Deploy Databases
        run: |
          kubectl apply -f k8s/product-db.yaml -n production
          kubectl apply -f k8s/order-db.yaml -n production
          kubectl apply -f k8s/customer-db.yaml -n production

      - name: Deploy Services
        run: |
          kubectl apply -f k8s/product-service.yaml -n production
          kubectl apply -f k8s/order-service.yaml -n production
          kubectl apply -f k8s/customer-service.yaml -n production
          kubectl apply -f k8s/frontend.yaml -n production
