name: CI - Build, Test & Push Images

# Trigger: push to branch testing 
# A Chnage
on:
  push:
    branches:
      - testing

jobs:
  test_and_validate_backends:
    runs-on: ubuntu-latest

    services:
      # Product DB
      product_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: products
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      # Order DB
      order_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orders
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

      # Customer DB
      customer_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: customers
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5434:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/product_service/requirements.txt
          pip install -r backend/order_service/requirements.txt
          pip install -r backend/customer_service/requirements.txt

      - name: Validate product_service
        working-directory: backend/product_service
        run: python -m compileall .

      - name: Validate order_service
        working-directory: backend/order_service
        run: python -m compileall .

      - name: Validate customer_service
        working-directory: backend/customer_service
        run: python -m compileall .

  # Job 2: Build and Push Docker Images (runs only if validation succeeds)
  build_and_push_images:
    runs-on: ubuntu-latest
    needs: test_and_validate_backends

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push Product Service Image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.ACR_LOGIN_SERVER }}/product_service:latest ./backend/product_service
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/product_service:latest

      - name: Build & Push Order Service Image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.ACR_LOGIN_SERVER }}/order_service:latest ./backend/order_service
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/order_service:latest

      - name: Build & Push Customer Service Image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:latest ./backend/customer_service
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:latest

      - name: Build & Push Frontend Image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest ./frontend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest
